language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
script:
    - dotnet build loterias-net.sln -c Release
test_script:
    - dotnet test loterias-net.sln -c Release
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
